### ISSUE TITLE
The package shows the wrong slide number

### ISSUE THREAD

**Issue by fabianneuhaus** [PM25/SimplePlus-BeamerTheme#1]
First of all: A very nice and clean beamer theme 

The issue is that the slide number is increased if one uses highlights or similar effects within a frame. Below is a minimal example. Latex creates for the same slide two pdf pages, because the  items are revealed in two steps. However, it is the same slide and, thus, the slide number should not be increased, i.e., the slide number should show 1/1 on both pages. 

``\documentclass[aspectratio=169,xcolor=dvipsnames]{beamer}``

``\usetheme{SimplePlus}``
``\begin{document}``
``\begin{frame}``
``    \begin{itemize}``
``         \item abc``
``        \item<2> abc``
``  \end{itemize}``
``\end{frame}``
``\end{document}``

**Comment by fabianneuhaus** [comment]
possible solution: 
change line 10 in beamerinnerthemeSimplePlus.sty to
``\setbeamertemplate{footline}[frame number]``

**Comment by pm25** [comment]
Thanks to point out the problem!
I just fixed it.
